Month7/step1
AlexeyGamovWVS/Stellar-Burgers pull request #1
Opened 2022-11-18 07:17 UTC by AlexeyGamovWVS

Первая итерация первой сдачи проекта

2022-11-18 09:59 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы провели **отличную** работу на первом этапе вашего нового проекта, **добро пожаловать** в мир Реакта! 

В рамках вашего кода прекрасно соблюдается семантика, вёрстка соответствует макету, CSS чистый и аккуратный, код лаконичный и не содержит лишнего, структура проекта выполнена верно, выполнена оптимизация группировки элементов по типам, **так держать** 👍

Однако, для прохождения этапа вам следует внимательно ознакомиться с комментариями к вашей работе, оставленными в рамках ревью, и провести необходимые **корректировки** ("**Надо исправить**") в текущем PR (не закрывая его и не создавая новый), обратив особое внимание на следующие моменты:

- **Проект не запускается** по причине нарушения регистра букв в наименовании файлов - на регистрозависимых системах, например Windows, файлы `App.js` и `app.js` будут считаться разными, на UNIX-подобных: одинаковыми (https://disk.yandex.ru/i/8lMtd_hylpHx-A)
- Для компонентов с пропсами cледует описать `PropTypes`. Если в качестве пропсов передается объект или массив объектов, то в `propTypes` описана структура этого объекта;
- Не следует хранить в рамках одного файла несколько компонентов, хорошей практикой считается подход "один компонент - один файл" (в том числе и стилизация, если она уникальна для компонента). Он позволит вам улучшить читаемость вашего кода, уменьшить кол-во строк в файлах, облегчить дальнейшее тестирование компонентов;
- Согласно дизайну следует подсветить активный элемент заголовка (https://disk.yandex.ru/i/fvfGMCpHbjKxNA), в данный момент достаточно подсветить только "Конструктор", но в будущем этот стиль вам пригодится :)

Также, в рамках работы были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу, в том числе:

- **Компоненты на классах** постепенно уходят в прошлое, оставляя место новым **функциональным**, которые активно развивает как команда Реакта в новых версиях, так и разработчики различных библиотек, оптимизирующие свой функционал именно под новый подход (например активно используя хуки). Поэтому рекомендую вам постепенно перевести ваш проект на функциональные компоненты;
- **Варианты значений стейта** имеет смысл вынести в отдельные константы или объединить под одной константой, чтобы их было удобно переиспользовать в рамках файла и при необходимости изменить содержимое только в одном месте, вместо множества;
- **Разбиение на компоненты** - это отличная практика, однако не целесообразно разбивать слишком сильно, рассматривайте необходимость с точки зрения кол-ва выносимого кода (например выносить 1-2 строчки это излишне и усложняет дерево и вызывает необходимость проброса пропсов еще ниже) и возможности переиспользования компонента в других местах;

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

_Если у вас возникнут вопросы относительно комментариев к коду - пишите их в соответствующем треде или передайте их через вашего куратора. Обязательно найдём самое лучшее решение :)_

**Успешного вам рефакторинга и хорошего настроения!** 🐈

2022-11-18 09:59 UTC, randomroot commented on src/index.js
> +import App from './components/app/app.js';
🔴 **Нужно исправить:**

**Проект не запускается** по причине нарушения регистра букв в наименовании файла - на регистрозависимых системах, например Windows, файлы `App.js` и `app.js` будут считаться разными, на UNIX-подобных: одинаковыми

2022-11-18 09:59 UTC, randomroot commented on src/components/app/App.js
> +			<React.Fragment>
🟡 **Можно улучшить:**

Можно упростить запись компонента фрагмента через синтаксис:
```html
<>
  ...
</>
```

2022-11-18 09:59 UTC, randomroot commented on src/components/header/header.js
> +function NavLink(props) {
🔴 **Нужно исправить:**

**Здесь и далее:** Не следует хранить в рамках одного файла несколько компонентов, хорошей практикой считается подход "один компонент - один файл". Он позволит вам улучшить читаемость вашего кода, уменьшить кол-во строк в файлах, облегчить дальнейшее тестирование компонентов.

2022-11-18 09:59 UTC, randomroot commented on src/components/header/header.js
> +    <button className={props.className} type="button">
🔴 **Нужно исправить:**

Согласно семантике следует заменить компонент `button` на ссылку `<a href="#>...</a>`, т.к. по логике эти элементы хедера должны вести на другую страницу в проекте.

Отмечу, что в следующих спринтах вместо ссылки будет компонент `Link` из библиотеки `react-router`

2022-11-18 09:59 UTC, randomroot commented on src/components/app/App.js
> +class App extends React.Component {
🟡 **Можно улучшить:**

Компоненты на классах постепенно уходят в прошлое, оставляя место новым функциональным, которые активно развивает как команда Реакта в новых версиях, так и разработчики различных библиотек, оптимизирующие свой функционал именно под новый подход (например активно используя хуки).

Поэтому рекомендую вам постепенно перевести ваш проект на функциональные компоненты.

2022-11-18 09:59 UTC, randomroot commented on src/components/main/burger-constructor/burger-constructor.js
> +yourChoice.forEach((item) => (sum += item.price));
🟡 **Можно улучшить:**

Функцию `forEach` можно заменить на более подходящую для этого случая `reduce` (см. https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce)

2022-11-18 09:59 UTC, randomroot commented on src/components/main/burger-constructor/burger-constructor.js
> +    .reduce((prev, next) => prev + next, 0);
🟡 **Можно улучшить:**

Есть возможность оптимизации: имеет смысл оставить только одну функцию `reduce` и вести подсчет по формуле `prev + next.price`, чтобы не создавать дополнительный массив через функцию `map`

2022-11-18 09:59 UTC, randomroot commented on src/components/main/burger-constructor/burger-constructor.js
> +      <div className="mr-2" style={{ visibility: iconVis }}>
🔴 **Нужно исправить:**

Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2022-11-18 09:59 UTC, randomroot commented on src/components/main/burger-constructor/burger-constructor.js
> +        isLocked={position !== "default" ? true : false}
🟡 **Можно улучшить:**

Здесь не требуется тернарный оператор, т.к. выражение неравенства возвращает логическое значение

2022-11-18 09:59 UTC, randomroot commented on src/components/main/burger-constructor/burger-constructor.js
> +    <ul className={constructurStyles.primaryList}>
🟡 **Можно улучшить:**

Допущена орфографическая ошибка в слове `constructur`

2022-11-18 09:59 UTC, randomroot commented on src/components/main/burger-constructor/burger-constructor.js
> +        {components}
🟡 **Можно улучшить:**

Проверьте, нет ли здесь лишнего дублирования? Если так задумано, то вопрос снимается

2022-11-18 09:59 UTC, randomroot commented on src/components/main/burger-ingredients/burger-ingredients.js
> +  const [current, setCurrent] = React.useState("buns");
🟡 **Можно улучшить:**

Варианты значения стейта имеет смысл вынести в отдельные константы или объединить под одной константой, чтобы их было удобно переиспользовать в рамках файла и при необходимости изменить содержимое только в одном месте, вместо множества, например:
```typescript
const Tabs = {
  BUN: 'bun',
  SAUCE: 'sauce'
  ...
}

... = useState(Tabs.BUN)
```

2022-11-18 09:59 UTC, randomroot commented on src/components/main/burger-ingredients/burger-ingredients.js
> +function Image(props) {
🟡 **Можно улучшить:**

Разбиение на компоненты - это отличная практика, однако не целесообразно разбивать слишком сильно, рассматривайте необходимость с точки зрения кол-ва выносимого кода (например выносить 1-2 строчки это излишне и усложняет дерево и вызывает необходимость проброса пропсов еще ниже) и возможности переиспользования компонента в других местах.

Если рассмотреть в текущем файле то код компонентов `Name`, `Image` лучше вернуть в компонент IngredientRow, и возможно `Price` - это всё одна сущность карточки ингредиентов

2022-11-18 09:59 UTC, randomroot commented on src/components/main/burger-ingredients/burger-ingredients.js
> +    const productMap = (
🟡 **Можно улучшить:**

Название переменной подразумевает, что внутри содержится возможно объект/Map, а на деле - React компонент. Лучше именовать их так, чтобы было сразу очевидно разработчикам, что внутри (например `ingredientCard`)

2022-11-18 09:59 UTC, randomroot commented on src/components/main/burger-ingredients/burger-ingredients.js
> +function getIngredientsMap(data) {
🟢 **Отлично:**

Вы выбрали правильный подход, группируя элементы по типам за один проход 👍

2022-11-18 09:59 UTC, randomroot commented on src/components/main/burger-ingredients/burger-ingredients.js
> +        undefinedType.push(element);
🟡 **Можно улучшить:**

Ситуация, когда придёт неизвестный тип маловероятна, такой случай в целом необязательно собирать в отдельный массив, т.к. далее он нигде не используется :)

2022-11-19 12:05 UTC, AlexeyGamovWVS commented on src/components/app/App.js
> +import AppHeader from "../header/header";
я не очень понимаю, почему в гитхаб данный файл заливается с большой буквы, при условии что в программе он с маленькой: https://disk.yandex.ru/i/zuQcExVKIjNd9w

2022-11-19 21:50 UTC, randomroot commented on src/components/app/App.js
> +import AppHeader from "../header/header";
Добрый день, попробуйте воспользоваться принудительным добавлением в Git-e (см. https://daily-dev-tips.com/posts/git-basics-help-my-case-sensitive-filename-changes-dont-commit/)

2022-11-20 07:04 UTC, AlexeyGamovWVS commented on src/components/app/App.js
> +import AppHeader from "../header/header";
Добрый день! Сработало, спасибо =)

2022-11-20 09:39 UTC, randomroot requested changes
**Здравствуйте!**

Вы внесли **большое** кол-во правок и улучшений в ваш код, **круто**, что перешли на функциональные компоненты 👍 
Осталось сделать **пару небольших** дополнений и корректировок в ваш проект для успешного окончания работы над спринтом:

- Следует **скорректировать** импорт в `index.js` компонента `App` - он указывает на файл с большой буквы и проект, пока, не запускается;
- **Проверить и дополнить** `PropTypes` в компонентах, где отсутствует описание части пропсов;
- **Наименования** всех констант, расположенных вне компонентов или функций, следует привести к стилю `UPPER_CASE`. Исключения составляют только переменные значение которых описывают `PropTypes`, т.к. формально это не константы, а просто описание типизации.

**Хорошего настроения и отличных выходных!** 🐈

2022-11-20 09:39 UTC, randomroot commented on src/components/header/nav-link/nav-link.js
> +      <span className={`ml-2`} style={{ display: "inline-block" }}>
🔴 **Нужно исправить:**

Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2022-11-20 09:39 UTC, randomroot commented on src/components/header/nav-link/nav-link.js
> +        {props.children}
🟡 **Можно улучшить:**

`children` можно вынести в декомпозицию выше

2022-11-20 09:39 UTC, randomroot commented on src/components/header/nav-link/nav-link.js
> +};
🔴 **Нужно исправить:**

Следует также описать и `children` здесь

2022-11-20 09:39 UTC, randomroot commented on src/components/main/burger-constructor/burger-components/burger-components.js
> +    PropTypes.shape({
🟡 **Можно улучшить:**

Повторяющиеся `PropTypes` можно вынести в отдельную переменную и переиспользовать в разных файлах:

```js
const IngredientPropType = PropTypes.shape({...})

BurgerComponents.propTypes = {
  data: PropTypes.arrayOf(IngredientPropType.isRequired)
}
```

2022-11-20 09:39 UTC, randomroot commented on src/components/main/burger-constructor/burger-list-item/burger-list-item.js
> +  position: PropTypes.string,
🔴 **Нужно исправить:**

**Здесь и далее по коду:** к обязательным пропсам следует добавлять `isRequired` в конце

2022-11-20 09:39 UTC, randomroot commented on src/components/main/burger-ingredients/tabs/tabs.js
> +const tabStates = {
🔴 **Нужно исправить:**

Наименования всех констант, расположенных вне компонентов или функций, следует привести к стилю `UPPER_CASE`. Исключения составляют только переменные значение которых описывают `PropTypes`, т.к. формально это не константы, а просто описание типизации :)

2022-12-02 14:52 UTC, randomroot approved these changes
🟢 **Предварительный этап принят**

Вы **успешно** внесли необходимые изменения для завершения 1-ого этапа данного спринта.

**Текущий PR можно слить в `main` и приступать к выполнению основного этапа.** Напомню, что сдача работы происходит через эту же форму, однако изменения следует делать в новой ветке: `sprint-1/step-2`.

**Хорошего вам настроения и так держать!** 👍

2022-12-02 17:14 UTC, merged